






///*************************************************///
///                                                 ///
/// This file is auto-generated by T4 Text Template ///
///           DO NOT manually modify it!            ///
///                                                 ///
///*************************************************///

using System;
using ZBase.Foundation.Mvvm.Unions;

namespace ZBase.Foundation.Mvvm.ViewBinding.Adapters
{

    [Serializable]
    [Label("Byte ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(byte), toType: typeof(bool), order: 0)]
    public sealed class ByteToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out byte result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("SByte ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(sbyte), toType: typeof(bool), order: 0)]
    public sealed class SByteToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out sbyte result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Char ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(char), toType: typeof(bool), order: 0)]
    public sealed class CharToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out char result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Double ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(double), toType: typeof(bool), order: 0)]
    public sealed class DoubleToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out double result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Float ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(float), toType: typeof(bool), order: 0)]
    public sealed class FloatToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out float result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Int ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(int), toType: typeof(bool), order: 0)]
    public sealed class IntToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out int result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("UInt ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(uint), toType: typeof(bool), order: 0)]
    public sealed class UIntToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out uint result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Long ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(long), toType: typeof(bool), order: 0)]
    public sealed class LongToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out long result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("ULong ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(ulong), toType: typeof(bool), order: 0)]
    public sealed class ULongToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out ulong result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Short ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(short), toType: typeof(bool), order: 0)]
    public sealed class ShortToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out short result))
            {
                return result > 0;
            }

            return union;
        }
    }

    [Serializable]
    [Label("UShort ⇒ Bool", "Default")]
    [Adapter(fromType: typeof(ushort), toType: typeof(bool), order: 0)]
    public sealed class UShortToBoolAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out ushort result))
            {
                return result > 0;
            }

            return union;
        }
    }

}
