






///*************************************************///
///                                                 ///
/// This file is auto-generated by T4 Text Template ///
///           DO NOT manually modify it!            ///
///                                                 ///
///*************************************************///

using System;
using ZBase.Foundation.Mvvm.Unions;

namespace ZBase.Foundation.Mvvm.ViewBinding.Adapters
{

    [Serializable]
    [Label("Byte ⇒ Int", "Default")]
    [Adapter(fromType: typeof(byte), toType: typeof(int), order: 0)]
    public sealed class ByteToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out byte result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("SByte ⇒ Int", "Default")]
    [Adapter(fromType: typeof(sbyte), toType: typeof(int), order: 0)]
    public sealed class SByteToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out sbyte result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Char ⇒ Int", "Default")]
    [Adapter(fromType: typeof(char), toType: typeof(int), order: 0)]
    public sealed class CharToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out char result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Double ⇒ Int", "Default")]
    [Adapter(fromType: typeof(double), toType: typeof(int), order: 0)]
    public sealed class DoubleToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out double result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Float ⇒ Int", "Default")]
    [Adapter(fromType: typeof(float), toType: typeof(int), order: 0)]
    public sealed class FloatToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out float result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Int ⇒ Int", "Default")]
    [Adapter(fromType: typeof(int), toType: typeof(int), order: 0)]
    public sealed class IntToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out int result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("UInt ⇒ Int", "Default")]
    [Adapter(fromType: typeof(uint), toType: typeof(int), order: 0)]
    public sealed class UIntToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out uint result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Long ⇒ Int", "Default")]
    [Adapter(fromType: typeof(long), toType: typeof(int), order: 0)]
    public sealed class LongToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out long result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("ULong ⇒ Int", "Default")]
    [Adapter(fromType: typeof(ulong), toType: typeof(int), order: 0)]
    public sealed class ULongToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out ulong result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("Short ⇒ Int", "Default")]
    [Adapter(fromType: typeof(short), toType: typeof(int), order: 0)]
    public sealed class ShortToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out short result))
            {
                return (int)result;
            }

            return union;
        }
    }

    [Serializable]
    [Label("UShort ⇒ Int", "Default")]
    [Adapter(fromType: typeof(ushort), toType: typeof(int), order: 0)]
    public sealed class UShortToIntAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TryGetValue(out ushort result))
            {
                return (int)result;
            }

            return union;
        }
    }

}
