






///*************************************************///
///                                                 ///
/// This file is auto-generated by T4 Text Template ///
///           DO NOT manually modify it!            ///
///                                                 ///
///*************************************************///

using System;
using UnityEngine;
using ZBase.Foundation.Mvvm.ViewBinding;

namespace ZBase.Foundation.Mvvm.Unity.ViewBinding.Adapters
{

    [Serializable]
    [Label("Resources.Load<Sprite>(string)", "Default")]
    [Adapter(fromType: typeof(string), toType: typeof(Sprite), order: 0)]
    public sealed class SpriteResorcesAdapter : ResourcesAdapter<Sprite>
    {
    }

    [Serializable]
    [Label("Resources.Load<GameObject>(string)", "Default")]
    [Adapter(fromType: typeof(string), toType: typeof(GameObject), order: 0)]
    public sealed class GameObjectResorcesAdapter : ResourcesAdapter<GameObject>
    {
    }

    [Serializable]
    [Label("Resources.Load<AudioClip>(string)", "Default")]
    [Adapter(fromType: typeof(string), toType: typeof(AudioClip), order: 0)]
    public sealed class AudioClipResorcesAdapter : ResourcesAdapter<AudioClip>
    {
    }

}
