namespace ZBase.Foundation.Mvvm.ViewBinding
{
    /// <summary>
    /// Any class implements this interface will be an eligible
    /// candidate to have its details generated by the corresponding generator.
    /// </summary>
    /// <seealso cref="BindingAttribute"/>
    public interface IBinder
    {
        IDataContext DataContext { get; }

        /// <summary>
        /// Binds an observable property to a binding field.
        /// </summary>
        /// <param name="propertyName">The name of an observable property whose container class is an <see cref="IObservableObject"/>.</param>
        /// <param name="bindingMethodName">The name of a [Binding] method of this binder.</param>
        bool BindPropertyTo(string propertyName, string bindingMethodName);

        /// <summary>
        /// Start receiving events from the <see cref="DataContext"/>.
        /// </summary>
        void StartBinding();

        /// <summary>
        /// Stop receiving any event from the <see cref="DataContext"/>.
        /// </summary>
        void StopBinding();
    }
}
