using System;

namespace ZBase.Foundation.Mvvm.ViewBinding
{
    /// <summary>
    /// An attribute that indicates that a given field is generated by the Binder generator.
    /// </summary>
    /// <remarks>
    /// This attribute is not intended to be used directly by user code to decorate user-defined properties.
    /// <br/>
    /// However, it can be used in other contexts, such as reflection.
    /// </remarks>
    /// <seealso cref="BindingField"/>
    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    public sealed class GeneratedBindingFieldAttribute : Attribute { }
}
