namespace ZBase.Foundation.Mvvm
{
    /// <summary>
    /// Any class implements this interface will be an eligible
    /// candidate to have its details generated by the corresponding generators.
    /// </summary>
    /// <seealso cref="ObservablePropertyAttribute"/>
    /// <seealso cref="RelayCommandAttribute"/>
    public interface IObservableObject { }
}
