#if MVVM_VALUE_UNION_SIZE_16_BYTES || MVVM_VALUE_UNION_SIZE_24_BYTES || MVVM_VALUE_UNION_SIZE_32_BYTES || MVVM_VALUE_UNION_SIZE_40_BYTES || MVVM_VALUE_UNION_SIZE_48_BYTES || MVVM_VALUE_UNION_SIZE_56_BYTES || MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L2__
#endif

#if MVVM_VALUE_UNION_SIZE_24_BYTES || MVVM_VALUE_UNION_SIZE_32_BYTES || MVVM_VALUE_UNION_SIZE_40_BYTES || MVVM_VALUE_UNION_SIZE_48_BYTES || MVVM_VALUE_UNION_SIZE_56_BYTES || MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L3__
#endif

#if MVVM_VALUE_UNION_SIZE_32_BYTES || MVVM_VALUE_UNION_SIZE_40_BYTES || MVVM_VALUE_UNION_SIZE_48_BYTES || MVVM_VALUE_UNION_SIZE_56_BYTES || MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L4__
#endif

#if MVVM_VALUE_UNION_SIZE_40_BYTES || MVVM_VALUE_UNION_SIZE_48_BYTES || MVVM_VALUE_UNION_SIZE_56_BYTES || MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L5__
#endif

#if MVVM_VALUE_UNION_SIZE_48_BYTES || MVVM_VALUE_UNION_SIZE_56_BYTES || MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L6__
#endif

#if MVVM_VALUE_UNION_SIZE_56_BYTES || MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L7__
#endif

#if MVVM_VALUE_UNION_SIZE_64_BYTES || MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L8__
#endif

#if MVVM_VALUE_UNION_SIZE_72_BYTES || MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L9__
#endif

#if MVVM_VALUE_UNION_SIZE_80_BYTES || MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L10__
#endif

#if MVVM_VALUE_UNION_SIZE_88_BYTES || MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L11__
#endif

#if MVVM_VALUE_UNION_SIZE_96_BYTES || MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L12__
#endif

#if MVVM_VALUE_UNION_SIZE_104_BYTES || MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L13__
#endif

#if MVVM_VALUE_UNION_SIZE_112_BYTES || MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L14__
#endif

#if MVVM_VALUE_UNION_SIZE_120_BYTES || MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L15__
#endif

#if MVVM_VALUE_UNION_SIZE_128_BYTES
#define __MVVM_VALUE_UNION_STORAGE_ENABLE_L16__
#endif

using System.Runtime.InteropServices;

namespace ZBase.Foundation.Mvvm
{
    /// <summary>
    /// Represents a unified layout to store the actual value for <see cref="Union"/>.
    /// </summary>
    /// <remarks>
    /// By default, the size is 8 bytes.
    /// <br />
    /// To resize, define one of the following symbols:
    /// <list type="bullet">
    /// <item><c>MVVM_VALUE_UNION_SIZE_16_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_24_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_32_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_40_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_48_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_56_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_64_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_72_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_80_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_88_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_96_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_104_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_112_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_120_BYTES</c></item>
    /// <item><c>MVVM_VALUE_UNION_SIZE_128_BYTES</c></item>
    /// </list>
    /// </remarks>
    [StructLayout(LayoutKind.Sequential)]
    public readonly struct UnionData
    {
        private readonly ulong _l1;

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L3__
        private readonly ulong _l2;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L3__
        private readonly ulong _l3;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L4__
        private readonly ulong _l4;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L5__
        private readonly ulong _l5;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L6__
        private readonly ulong _l6;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L7__
        private readonly ulong _l7;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L8__
        private readonly ulong _l8;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L9__
        private readonly ulong _l9;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L10__
        private readonly ulong _l10;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L11__
        private readonly ulong _l11;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L12__
        private readonly ulong _l12;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L13__
        private readonly ulong _l13;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L14__
        private readonly ulong _l14;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L15__
        private readonly ulong _l15;
#endif

#if __MVVM_VALUE_UNION_STORAGE_ENABLE_L16__
        private readonly ulong _l16;
#endif
    }
}
