






///*************************************************///
///                                                 ///
/// This file is auto-generated by T4 Text Template ///
///           DO NOT manually modify it!            ///
///                                                 ///
///*************************************************///

using System;
using ZBase.Foundation.Mvvm.Unions;

namespace ZBase.Foundation.Mvvm.ViewBinding.Adapters
{

    [Serializable]
    [Label("Bool ⇒ String", "Default")]
    [Adapter(typeof(bool), typeof(string))]
    public sealed class BoolToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Bool)
            {
                return union.Bool.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Byte ⇒ String", "Default")]
    [Adapter(typeof(byte), typeof(string))]
    public sealed class ByteToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Byte)
            {
                return union.Byte.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("SByte ⇒ String", "Default")]
    [Adapter(typeof(sbyte), typeof(string))]
    public sealed class SByteToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.SByte)
            {
                return union.SByte.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Char ⇒ String", "Default")]
    [Adapter(typeof(char), typeof(string))]
    public sealed class CharToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Char)
            {
                return union.Char.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Double ⇒ String", "Default")]
    [Adapter(typeof(double), typeof(string))]
    public sealed class DoubleToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Double)
            {
                return union.Double.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Float ⇒ String", "Default")]
    [Adapter(typeof(float), typeof(string))]
    public sealed class FloatToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Float)
            {
                return union.Float.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Int ⇒ String", "Default")]
    [Adapter(typeof(int), typeof(string))]
    public sealed class IntToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Int)
            {
                return union.Int.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("UInt ⇒ String", "Default")]
    [Adapter(typeof(uint), typeof(string))]
    public sealed class UIntToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.UInt)
            {
                return union.UInt.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Long ⇒ String", "Default")]
    [Adapter(typeof(long), typeof(string))]
    public sealed class LongToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Long)
            {
                return union.Long.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("ULong ⇒ String", "Default")]
    [Adapter(typeof(ulong), typeof(string))]
    public sealed class ULongToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.ULong)
            {
                return union.ULong.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("Short ⇒ String", "Default")]
    [Adapter(typeof(short), typeof(string))]
    public sealed class ShortToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.Short)
            {
                return union.Short.ToString();
            }

            return union;
        }
    }

    [Serializable]
    [Label("UShort ⇒ String", "Default")]
    [Adapter(typeof(ushort), typeof(string))]
    public sealed class UShortToStringAdapter : IAdapter
    {
        public Union Convert(in Union union)
        {
            if (union.TypeKind == UnionTypeKind.UShort)
            {
                return union.UShort.ToString();
            }

            return union;
        }
    }

}
